import Preset from '../types/preset';

const PRESETS = [
  {
    name: 'Creme De la Creme',
    tempo: '112',
    volume: '1.2',
    voices: {
      BD: {
        volume: '0.7',
        pitch: '-700',
        pattern: [
          true,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
        ],
      },
      CB: {
        volume: '0.4',
        pitch: '-1400',
        pattern: [
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
      },
      CH: {
        volume: '0.9',
        pitch: '-750',
        pattern: [
          true,
          true,
          true,
          false,
          true,
          false,
          true,
          false,
          true,
          false,
          false,
          true,
          true,
          false,
          false,
          true,
        ],
      },
      CL: {
        volume: 1,
        pitch: 0,
        pattern: [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
      },
      CP: {
        volume: '1.1',
        pitch: '-650',
        pattern: [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
        ],
      },
      CY: {
        volume: '0.6',
        pitch: '-250',
        pattern: [
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
        ],
      },
      HC: {
        volume: '1',
        pitch: '0',
        pattern: [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
      },
      HT: {
        volume: 1,
        pitch: 0,
        pattern: [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
      },
      LT: {
        volume: 1,
        pitch: 0,
        pattern: [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
      },
      MA: {
        volume: '0.3',
        pitch: '-1150',
        pattern: [
          true,
          false,
          true,
          false,
          true,
          false,
          true,
          false,
          true,
          false,
          true,
          false,
          true,
          false,
          true,
          false,
        ],
      },
      OH: {
        volume: '0.7',
        pitch: '200',
        pattern: [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
      },
      RS: {
        volume: '0.9',
        pitch: '400',
        pattern: [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
      },
      SD: {
        volume: '0.6',
        pitch: '0',
        pattern: [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
      },
    },
  },
  {
    name: 'Cybertron',
    tempo: 140,
    volume: 1,
    voices: {
      BD: {
        volume: 1,
        pitch: 0,
        pattern: [
          true,
          false,
          false,
          true,
          true,
          false,
          true,
          false,
          false,
          false,
          true,
          false,
          true,
          false,
          false,
          false,
        ],
      },
      CB: {
        volume: 1,
        pitch: 0,
        pattern: [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
      },
      CH: {
        volume: 1,
        pitch: 0,
        pattern: [
          true,
          true,
          true,
          true,
          false,
          false,
          false,
          false,
          true,
          true,
          true,
          true,
          false,
          false,
          false,
          false,
        ],
      },
      CL: {
        volume: 1,
        pitch: 0,
        pattern: [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
      },
      CP: {
        volume: 1,
        pitch: 0,
        pattern: [
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
        ],
      },
      CY: {
        volume: 1,
        pitch: 0,
        pattern: [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
      },
      HC: {
        volume: 1,
        pitch: 0,
        pattern: [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
      },
      HT: {
        volume: 1,
        pitch: 0,
        pattern: [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
      },
      LT: {
        volume: 1,
        pitch: 0,
        pattern: [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
      },
      MA: {
        volume: 1,
        pitch: 0,
        pattern: [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
      },
      OH: {
        volume: 1,
        pitch: 0,
        pattern: [
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
        ],
      },
      RS: {
        volume: 1,
        pitch: 0,
        pattern: [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
      },
      SD: {
        volume: 1,
        pitch: 0,
        pattern: [
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
        ],
      },
    },
  },
  {
    name: 'blank',
    tempo: 120,
    volume: 1,
    voices: {
      BD: {
        volume: 1,
        pitch: 0,
        pattern: [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
      },
      CB: {
        volume: 1,
        pitch: 0,
        pattern: [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
      },
      CH: {
        volume: 1,
        pitch: 0,
        pattern: [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
      },
      CL: {
        volume: 1,
        pitch: 0,
        pattern: [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
      },
      CP: {
        volume: 1,
        pitch: 0,
        pattern: [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
      },
      CY: {
        volume: 1,
        pitch: 0,
        pattern: [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
      },
      HC: {
        volume: 1,
        pitch: 0,
        pattern: [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
      },
      HT: {
        volume: 1,
        pitch: 0,
        pattern: [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
      },
      LT: {
        volume: 1,
        pitch: 0,
        pattern: [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
      },
      MA: {
        volume: 1,
        pitch: 0,
        pattern: [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
      },
      OH: {
        volume: 1,
        pitch: 0,
        pattern: [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
      },
      RS: {
        volume: 1,
        pitch: 0,
        pattern: [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
      },
      SD: {
        volume: 1,
        pitch: 0,
        pattern: [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
      },
    },
  },
];

export default PRESETS as Preset[];
