import Preset from '../types/preset';

const PRESETS = [
  {
    name: 'cybertron',
    tempo: 140,
    volume: 0.8,
    voices: {
      BD: {
        volume: 0.8,
        pitch: 0,
        pattern: [
          true,
          false,
          false,
          true,
          true,
          false,
          true,
          false,
          false,
          false,
          true,
          false,
          true,
          false,
          false,
          false,
        ],
      },
      CB: {
        volume: 0.8,
        pitch: 0,
        pattern: [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
      },
      CH: {
        volume: 0.8,
        pitch: 0,
        pattern: [
          true,
          true,
          true,
          true,
          false,
          false,
          false,
          false,
          true,
          true,
          true,
          true,
          false,
          false,
          false,
          false,
        ],
      },
      CL: {
        volume: 0.8,
        pitch: 0,
        pattern: [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
      },
      CP: {
        volume: 0.8,
        pitch: 0,
        pattern: [
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
        ],
      },
      CY: {
        volume: 0.8,
        pitch: 0,
        pattern: [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
      },
      HC: {
        volume: 0.8,
        pitch: 0,
        pattern: [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
      },
      HT: {
        volume: 0.8,
        pitch: 0,
        pattern: [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
      },
      LT: {
        volume: 0.8,
        pitch: 0,
        pattern: [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
      },
      MA: {
        volume: 0.8,
        pitch: 0,
        pattern: [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
      },
      OH: {
        volume: 0.8,
        pitch: 0,
        pattern: [
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
        ],
      },
      RS: {
        volume: 0.8,
        pitch: 0,
        pattern: [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
      },
      SD: {
        volume: 0.8,
        pitch: 0,
        pattern: [
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
        ],
      },
    },
  },
  {
    name: 'blank',
    tempo: 120,
    volume: 0.8,
    voices: {
      BD: {
        volume: 0.8,
        pitch: 0,
        pattern: [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
      },
      CB: {
        volume: 0.8,
        pitch: 0,
        pattern: [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
      },
      CH: {
        volume: 0.8,
        pitch: 0,
        pattern: [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
      },
      CL: {
        volume: 0.8,
        pitch: 0,
        pattern: [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
      },
      CP: {
        volume: 0.8,
        pitch: 0,
        pattern: [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
      },
      CY: {
        volume: 0.8,
        pitch: 0,
        pattern: [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
      },
      HC: {
        volume: 0.8,
        pitch: 0,
        pattern: [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
      },
      HT: {
        volume: 0.8,
        pitch: 0,
        pattern: [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
      },
      LT: {
        volume: 0.8,
        pitch: 0,
        pattern: [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
      },
      MA: {
        volume: 0.8,
        pitch: 0,
        pattern: [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
      },
      OH: {
        volume: 0.8,
        pitch: 0,
        pattern: [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
      },
      RS: {
        volume: 0.8,
        pitch: 0,
        pattern: [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
      },
      SD: {
        volume: 0.8,
        pitch: 0,
        pattern: [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        ],
      },
    },
  },
];

export default PRESETS as Preset[];
